' Gambas module file

'    This file is part of vpackager

'    vpackager is free software: you can redistribute it and/or modify
'    it under the terms of the GNU General Public License as published by
'    the Free Software Foundation, either version 3 of the License, or
'    (at your option) any later version.

'    vpackager  is distributed in the hope that it will be useful,
'    but WITHOUT ANY WARRANTY; without even the implied warranty of
'    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
'    GNU General Public License for more details.

'    You should have received a copy of the GNU General Public License
'    along with vpackager.  If not, see <http://www.gnu.org/licenses/>.



' Will hold all the functions to the description writer
PUBLIC SUB Load_Values()
  
  IF ClsBuildVars.sName THEN 
    SlackDescWriter.sName = ClsBuildVars.sName
    SlackDescWriter.sVer = ClsBuildVars.sVersion
    FNewSlackDesc.AppNameBox.Text = SlackDescWriter.sName
  ' ' 
  ' ' IF Global.sAPP THEN 
  ' '   SlackDescWriter.sName = Global.sAPP
  ' '   SlackDescWriter.sVer = Global.sVer
  ' '   FNewSlackDesc.AppNameBox.text = SlackDescWriter.sName
   
  ELSE 
  Message.Info("Looks like we are just writing a slack-desc file, but not building a package")
  END IF
    
END


