' Gambas module file

'    This file is part of vpackager

'    vpackager is free software: you can redistribute it and/or modify
'    it under the terms of the GNU General Public License as published by
'    the Free Software Foundation, either version 3 of the License, or
'    (at your option) any later version.

'    vpackager  is distributed in the hope that it will be useful,
'    but WITHOUT ANY WARRANTY; without even the implied warranty of
'    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
'    GNU General Public License for more details.

'    You should have received a copy of the GNU General Public License
'    along with vpackager.  If not, see <http://www.gnu.org/licenses/>.

' /* The make install procedure will be shared between the GNU and CMAKE build types

PUBLIC SUB RUN_MAKEINSTALL(sBuildDir AS String)
  
  DIM sShellcmd AS String
  DIM bClear AS Boolean
  
  IF IsDir(sBuildDir &/ "PKG") = FALSE THEN 
    MKDIR sBuildDir &/ "PKG"
  END IF
  sShellcmd = "cd " & sBuildDir & " ; make DESTDIR=$PWD/PKG install"
  
  mdlSrcBuild.RUN_SHELL(sShellcmd)
    IF MdlSrcBuild.hproc.State = Process.Running THEN 
        REPEAT 
          WAIT 
        UNTIL 
    MdlSrcBuild.hproc.State = Process.Stopped
    END IF
    bClear = MdlSrcBuild.ERROR_TEST("FAILED", FrmBuildView.taTerm.Text)
    'MdlSrcBuild.iStepInProcedure = 4
    FrmBuildView.PbBuildProg.Value = 0.78
        
      IF bClear = TRUE THEN 
        MdlMain.WRITE_TO_BUILD_LOG("An error occurred in the build process... Please check the build log")
        MdlSrcBuild.TOGGLE_BUILD_CANCEL(FALSE)
        RETURN ' STOP HERE.... NOT CLEAR
      ELSE 
        ' Ready to go,.... no errors.... 
        ' Package it up now
          
        MdlMain.WRITE_TO_BUILD_LOG(" + Create installable package")
        MdlPackage.PACKAGE(sBuildDir &/ "PKG")
        
      END IF
  
END
