' Gambas module file

'    This file is part of vpackager

'    vpackager is free software: you can redistribute it and/or modify
'    it under the terms of the GNU General Public License as published by
'    the Free Software Foundation, either version 3 of the License, or
'    (at your option) any later version.

'    vpackager  is distributed in the hope that it will be useful,
'    but WITHOUT ANY WARRANTY; without even the implied warranty of
'    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
'    GNU General Public License for more details.

'    You should have received a copy of the GNU General Public License
'    along with vpackager.  If not, see <http://www.gnu.org/licenses/>.



PUBLIC SUB POPULATE_GRID()
  'DIM r AS Integer
  'DIM c AS Integer
 DIM i AS Integer
  DIM sList AS String
  DIM sItems AS string[]
  DIM sCurrentRepo AS String
  DIM sFixedCurrent AS String
  DIM sDisabled AS String
  DIM sDisabledItems AS String[]
  DIM ii AS Integer
  DIM sCurrentDis AS String
  DIM sFixedCurrentDis AS String
  DIM iii AS Integer 'gridindex
  DIM sCurrentfield AS Integer
  DIM sLongList AS String
  DIM sRepoList AS String[]
  'DIM i_Enabled AS Integer = FRepChange.tlEnabled.BackColor
  'DIM i_Disabled AS Integer = FRepChange.tlDisabled.BackColor
  
  ' Check to make sure the dir exists, and create if necessary the "disabled " dir
  IF NOT IsDir(CRepChange.sDisabledPath) THEN 
    'message.Warning("Directory does not exit")
    TRY MKDIR CRepChange.sDisabledPath
    IF ERROR THEN 
      SHELL "mkdir -p " & CRepChange.sDisabledPath
      END IF
    'CATCH 
  END IF
  
  
    
  'SHELL "ls -h /etc/ports | grep httpup" TO sList
  SHELL "ls -h " & CRepChange.sEnabledPath & " | grep httpup" TO sList
  CRepChange.sEnabledRepos = sList
  'SHELL "ls -h /etc/ports/disabled | grep httpup" TO sDisabled
  SHELL "ls -h " & CRepChange.sDisabledPath & " | grep httpup" TO sDisabled
  CRepChange.sDisabledList = sDisabled
  sLongList = sList & sDisabled
  sRepoList = Split(sLongList, "\n")
  
  FRepChange.gvRepos.Rows.Count = sRepoList.Count
  
  FRepChange.gvRepos.columns.Count = 3
    
    FRepChange.gvRepos.Columns[0].Width = 10
    FRepChange.gvRepos.Columns[1].Width = 160
    FRepChange.gvRepos.Columns[1].Title = "Ports Collection"
    FRepChange.gvRepos.Columns[2].Title = "Source URL"
    
        
FOR i = 0 TO sRepoList.Count - 1

  sCurrentRepo = sRepoList[i]
  sFixedCurrent = Left(sCurrentRepo, Len(sCurrentRepo) - 7)
  
  IF InStr(sList, sCurrentRepo) THEN 
 FRepChange.gvRepos[i, 0].BackColor = &h4C9F09 'color.Darkgreen
 SHELL "cat " & CRepChange.sEnabledPath &/ sFixedCurrent & ".httpup | grep URL=" TO CRepChange.sRepoFile 
  CRepChange.sRepoSrcUrl = Right(CRepChange.sRepoFile, Len(CRepChange.sRepoFile) - Len("URL="))
  FRepChange.gvRepos[i, 2].text = CRepChange.sRepoSrcUrl
 ELSE IF InStr(sDisabled, sCurrentRepo) THEN 
  SHELL "cat " & CRepChange.sDisabledPath &/ sFixedCurrent & ".httpup | grep URL=" TO CRepChange.sRepoFile
  CRepChange.sRepoSrcUrl = Right(CRepChange.sRepoFile, Len(CRepChange.sRepoFile) - Len("URL="))
 FRepChange.gvRepos[i, 0].BackColor = &hDF4343 ' Color.red
 FRepChange.gvRepos[i, 2].text = CRepChange.sRepoSrcUrl
 END IF
  FRepChange.gvRepos[i, 1].text = sFixedCurrent
  
  NEXT
  
 
        
END

PUBLIC SUB REP_ENABLE()
  DIM sRepname AS String
  
  sRepname = CRepChange.sSelectedRepo & ".httpup" ' Add the httpup to the file name again
  'message.Info(sRepname)
  
   TRY MOVE CRepChange.sDisabledPath &/ sRepname TO CRepChange.sEnabledPath &/ sRepname
    IF ERROR THEN 
       SHELL "mv " & CRepChange.sDisabledPath &/ sRepname & " " & CRepChange.sEnabledPath &/ sRepname
     END IF
    
    ME.POPULATE_GRID() ' populate the grid again. hopefully, this wont result in error.
  
END

PUBLIC SUB REP_DISABLE()
  
  DIM sRepname AS String
  sRepname = CRepChange.sSelectedRepo & ".httpup"
  TRY MOVE CRepChange.sEnabledPath &/ sRepname TO CRepChange.sDisabledPath &/ sRepname
  IF ERROR THEN 
    SHELL "mv " & CRepChange.sEnabledPath &/ sRepname & " " & CRepChange.sDisabledPath &/ sRepname
    END IF
  ME.POPULATE_GRID()
  
END



